services:
  continuwuity-link-preview-updater:
    image: mikaff0/c10y-link-preview-updater:latest # ghcr.io/mikaff0/c10y-link-preview-updater:latest
    container_name: continuwuity-updater
    environment:
      - CRON_SCHEDULE=0 * * * *  # hourly o'clock
      # - TZ=Europe/Berlin         # Set your timezone (default: UTC)
      # Optional: Customize paths (default values shown below)
      # - TEMPLATE_PATH=/data/c10y.toml
      # - DB_PATH=/data/morpheus link bot.db
      # - OUTPUT_PATH=/data/continuwuity.toml
    volumes:
      - /path/to/maubot/dbs/morpheus link bot.db:/data/morpheus link bot.db:ro
      - /path/to/your/c10y.toml:/data/c10y.toml:ro
      - /path/to/your/continuwuity.toml:/data/continuwuity.toml:rw
    restart: unless-stopped